apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-bank-gateway-config
  namespace: blue-bank
data:
  SPRING_PROFILES_ACTIVE: prod
  REDIS_HOST: prod-redis.example.internal
  REDIS_PORT: "6379"
  DATACENTER: nks-kr
