apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: blue-bank-gateway
    newName: REGISTRY_NAME.kr.ncr.ntruss.com/blue-bank-gateway
    newTag: prod
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: delete-redis-service.yaml
  - path: delete-redis-statefulset.yaml
