apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-bank-gateway-config
  namespace: blue-bank
data:
  SPRING_PROFILES_ACTIVE: dev
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  SERVICES_ACCOUNT_URL: http://blue-bank-account:8100
  SERVICES_DEPOSIT_URL: http://blue-bank-deposit:8200
  SERVICES_LOAN_URL: http://blue-bank-loan:8300
  SERVICES_CARD_URL: http://blue-bank-card:8400
