apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blue-bank-gateway
  namespace: blue-bank
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blue-bank-gateway
