apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blue-bank
resources:
  - namespace.yaml
  - configmap.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - gateway-pdb.yaml
  - gateway-hpa.yaml
  - gateway-api.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: blue-bank
