apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: blue-bank-gateway
    newName: blue-bank-dev.kr.ncr.ntruss.com/blue-bank-gateway
    newTag: dev-6ea06f700c5606fd868c2963dcee10f0618f6bde
