apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: blue-bank-gateway
    newName: blue-bank-dev.kr.ncr.ntruss.com/blue-bank-gateway
    newTag: dev-ef6c1f3
