apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: blue-bank-gateway
    newName: blue-bank-dev.kr.ncr.ntruss.com/blue-bank-gateway
    newTag: dev-63f6cc7916f9dc9b62312d086e19a0d92b7fef77
